config/routes.rb
Likes::Application.routes.draw do
  resources :dealattendees

  resources :deals

  resources :products

  resources :cities

  resources :microposts

  resources :users

end

app/models/dealattendee.rb
class Dealattendee < ActiveRecord::Base
             belongs_to :deal
             belongs_to :user
end

app/controllers/dealattendees_controller.rb
class DealattendeesController < ApplicationController
  # GET /dealattendees
  # GET /dealattendees.xml
  def index
    @dealattendees = Dealattendee.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dealattendees }
    end
  end

  # GET /dealattendees/1
  # GET /dealattendees/1.xml
  def show
    @dealattendee = Dealattendee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dealattendee }
    end
  end

  # GET /dealattendees/new
  # GET /dealattendees/new.xml
  def new
    @dealattendee = Dealattendee.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dealattendee }
    end
  end

  # GET /dealattendees/1/edit
  def edit
    @dealattendee = Dealattendee.find(params[:id])
  end

  # POST /dealattendees
  # POST /dealattendees.xml
  def create
    @dealattendee = Dealattendee.new(params[:dealattendee])

    respond_to do |format|
      if @dealattendee.save
        format.html { redirect_to(@dealattendee, :notice => 'Dealattendee was successfully created.') }
        format.xml  { render :xml => @dealattendee, :status => :created, :location => @dealattendee }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dealattendee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dealattendees/1
  # PUT /dealattendees/1.xml
  def update
    @dealattendee = Dealattendee.find(params[:id])

    respond_to do |format|
      if @dealattendee.update_attributes(params[:dealattendee])
        format.html { redirect_to(@dealattendee, :notice => 'Dealattendee was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dealattendee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dealattendees/1
  # DELETE /dealattendees/1.xml
  def destroy
    @dealattendee = Dealattendee.find(params[:id])
    @dealattendee.destroy

    respond_to do |format|
      format.html { redirect_to(dealattendees_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dealattendees_helper.rb
module DealattendeesHelper
end

app/views/dealattendees/_form.html.erb
<%= form_for(@dealattendee) do |f| %>
  <% if @dealattendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealattendee.errors.count, "error") %> prohibited this dealattendee from being saved:</h2>

      <ul>
      <% @dealattendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deal_id %><br />
    <%= f.text_field :deal_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dealattendees/edit.html.erb
<h1>Editing dealattendee</h1>

<%= render 'form' %>

<%= link_to 'Show', @dealattendee %> |
<%= link_to 'Back', dealattendees_path %>

app/views/dealattendees/index.html.erb
<h1>Listing dealattendees</h1>

<table>
  <tr>
    <th>Deal</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dealattendees.each do |dealattendee| %>
  <tr>
    <td><%= dealattendee.deal_id %></td>
    <td><%= dealattendee.user_id %></td>
    <td><%= link_to 'Show', dealattendee %></td>
    <td><%= link_to 'Edit', edit_dealattendee_path(dealattendee) %></td>
    <td><%= link_to 'Destroy', dealattendee, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dealattendee', new_dealattendee_path %>

app/views/dealattendees/new.html.erb
<h1>New dealattendee</h1>

<%= render 'form' %>

<%= link_to 'Back', dealattendees_path %>

app/views/dealattendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Deal:</b>
  <%= @dealattendee.deal_id %>
</p>

<p>
  <b>User:</b>
  <%= @dealattendee.user_id %>
</p>


<%= link_to 'Edit', edit_dealattendee_path(@dealattendee) %> |
<%= link_to 'Back', dealattendees_path %>